In [1]:
import xarray as xr
import rasterio as rio
import geopandas as gpd
import rasterstats as rstats

In [4]:
# netcdf file loader
ds = xr.open_dataset(r"C:\Users\Kris\Documents\amazonforcast\data\prakrut\LIS_HIST_Forecast_June_02_to_05.nc")

# shp file loader
hybas_sa_lev05 = gpd.read_file(r"C:\Users\Kris\Documents\amazonforcast\gisfiles\hydrobasins shape\hybas_sa_lev05_areaofstudy.shp")

# Create a list for the variable names
list_of_variables = ['Rainf_tavg','SoilMoist_inst','Qs_tavg','Evap_tavg','SoilTemp_inst','Qair_f_tavg'] 

In [8]:
ds

<xarray.Dataset>
Dimensions:           (time: 4, north_south: 540, east_west: 660, ensemble: 7,
                       SoilMoist_profiles: 4, SoilTemp_profiles: 4)
Coordinates:
  * time              (time) datetime64[ns] 2024-06-02 2024-06-03 ... 2024-06-05
  * ensemble          (ensemble) float32 1.0 2.0 3.0 4.0 5.0 6.0 7.0
  * north_south       (north_south) float64 -21.0 -20.95 -20.9 ... 5.9 5.95 6.0
  * east_west         (east_west) float64 -82.0 -81.95 -81.9 ... -49.05 -49.0
Dimensions without coordinates: SoilMoist_profiles, SoilTemp_profiles
Data variables: (12/32)
    lat               (time, north_south) float32 ...
    lon               (time, east_west) float32 ...
    Swnet_tavg        (time, ensemble, north_south, east_west) float32 ...
    Lwnet_tavg        (time, ensemble, north_south, east_west) float32 ...
    Qle_tavg          (time, ensemble, north_south, east_west) float32 ...
    Qh_tavg           (time, ensemble, north_south, east_west) float32 ...
    ...                ...
    Qair_f_tavg       (time, ensemble, north_south, east_west) float32 ...
    Psurf_f_tavg      (time, ensemble, north_south, east_west) float32 ...
    SWdown_f_tavg     (time, ensemble, north_south, east_west) float32 ...
    LWdown_f_tavg     (time, ensemble, north_south, east_west) float32 ...
    LAI_inst          (time, ensemble, north_south, east_west) float32 ...
    Greenness_inst    (time, ensemble, north_south, east_west) float32 ...
Attributes: (12/15)
    missing_value:           -9999.0
    NUM_SOIL_LAYERS:         4
    SOIL_LAYER_THICKNESSES:  [ 10.        30.000002  60.000004 100.      ]
    title:                   LIS land surface model output
    institution:             NASA GSFC
    source:                  
    ...                      ...
    comment:                 website: http://lis.gsfc.nasa.gov/
    MAP_PROJECTION:          EQUIDISTANT CYLINDRICAL
    SOUTH_WEST_CORNER_LAT:   -20.975
    SOUTH_WEST_CORNER_LON:   -81.975
    DX:                      0.05
    DY:                      0.05

In [7]:
hybas_sa_lev05

HYBAS_ID     NEXT_DOWN     NEXT_SINK      MAIN_BAS  DIST_SINK  \
0    6.050134e+09  6.050102e+09  6.050004e+09  6.050004e+09     1275.6   
1    6.050135e+09  6.050134e+09  6.050004e+09  6.050004e+09     1278.6   
2    6.050135e+09  6.050134e+09  6.050004e+09  6.050004e+09     1278.6   
3    6.050137e+09  6.050135e+09  6.050004e+09  6.050004e+09     1307.0   
4    6.050137e+09  6.050135e+09  6.050004e+09  6.050004e+09     1307.2   
..            ...           ...           ...           ...        ...   
146  6.050033e+09  0.000000e+00  6.050033e+09  6.050033e+09        0.0   
147  6.050034e+09  0.000000e+00  6.050034e+09  6.050034e+09        0.0   
148  6.050034e+09  0.000000e+00  6.050034e+09  6.050034e+09        0.0   
149  6.050034e+09  0.000000e+00  6.050034e+09  6.050034e+09        0.0   
150  6.050040e+09  0.000000e+00  6.050040e+09  6.050040e+09        0.0   

     DIST_MAIN  SUB_AREA   UP_AREA  PFAF_ID  ENDO  COAST  ORDER_   SORT  \
0       1275.6    2264.6  100975.1    61581     0      0       2   42.0   
1       1278.6     363.7  139064.0    61593     0      0       1   43.0   
2       1278.6   12532.3   12532.3    61592     0      0       2   44.0   
3       1307.0   13041.0   84883.0    61595     0      0       1   49.0   
4       1307.2   53814.6   53816.9    61594     0      0       2   50.0   
..         ...       ...       ...      ...   ...    ...     ...    ...   
146        0.0   22671.2   22671.2    67205     0      1       0  453.0   
147        0.0   22420.9   22420.9    67206     0      0       1  454.0   
148        0.0   22325.0   22325.0    67207     0      1       0  455.0   
149        0.0   15397.6   15397.6    67208     0      0       1  456.0   
150        0.0  146228.6  146228.6    66405     2      0       1  466.0   

     Shape_Leng  Shape_Area                                           geometry  
0      2.682938    0.183604  POLYGON ((-7534938.033 449359.896, -7535322.99...  
1      0.943771    0.029483  POLYGON ((-7547461.476 429832.689, -7549122.85...  
2      7.085708    1.015267  POLYGON ((-7584567.973 324822.167, -7584631.12...  
3      9.702607    1.056988  POLYGON ((-7790972.862 329466.582, -7791080.59...  
4     16.338734    4.357097  POLYGON ((-7674551.228 389396.061, -7674590.56...  
..          ...         ...                                                ...  
146   12.094961    1.833940  MULTIPOLYGON (((-8770275.16 203192.432, -87723...  
147    9.568663    1.814174  POLYGON ((-8615664.756 95088.921, -8615570.031...  
148   11.275923    1.807964  MULTIPOLYGON (((-8601904.43 445640.11, -860257...  
149    7.164665    1.249452  POLYGON ((-8610098.782 458660.033, -8610832.50...  
150   26.228833   12.387341  MULTIPOLYGON (((-7699134.282 -1661844.226, -77...  

[151 rows x 16 columns]

Define coordinates for the dimensions without coordinates
    
```
north_south_coords = np.linspace(-21, 6, num=540)  # Example coordinates for "north_south" dimension

east_west_coords = np.linspace(-82, -49, num=660)  # Example coordinates for "east_west" dimension
```

In [21]:
## Define function that load each variables from the dataset
def load_var_from_ds (dataset, list_vars):
    for vars in list_vars:
        globals()[vars] = dataset[f'{vars}']
    
    ds.close()
    return

In [ ]:
## Define function to output the 